server:
  port: 8888

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8010/eureka/ #eureka服务注册地址

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fengzp/config/ #git仓库地址
          searchPaths: demo* #搜索路径
#          username: username
#          password: password
  application:
    name: config-server